name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Changer en fonction de votre branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14  # Choisir la version de Node.js appropriée

      - name: Install dependencies
        run: npm install

      - name: Build Vue.js app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main  # Changer en fonction de votre branche de déploiement
          FOLDER: dist      # Changer en fonction de votre dossier de build

